WITH CTE1 AS
(SELECT
CASE WHEN ORDER_DATE=customer_pref_delivery_date THEN 1 ELSE 0 END AS TYPE,
ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date) AS FIRST_ORDER
FROM
DELIVERY)

(SELECT ROUND((SUM(CASE WHEN TYPE=1 THEN 1 END)/COUNT(TYPE))*100,2) AS immediate_percentage FROM CTE1 WHERE FIRST_ORDER=1)